---
swagger: "2.0"
info:
  version: "0.0.2"
  title: "api-server"
host: "localhost:5000"
basePath: "/"
schemes:
- "http"
- "https"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /content:
    get:
      tags:
      - "Content"
      description: "Returns 'Hello' to the caller"
      operationId: "retrieve"
      parameters:
      - name: "name"
        in: "query"
        description: "The name of the person to whom to say hello"
        required: false
        type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/HelloWorldResponse"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
      x-swagger-router-controller: "Content"
    put:
      tags:
      - "Content"
      description: "Put me a json content package"
      operationId: "create"
      parameters:
      - in: "body"
        name: "body"
        description: "a valid json file"
        required: true
        schema:
          $ref: "#/definitions/contentSchema"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/HelloWorldResponse"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
      x-swagger-router-controller: "Content"
    x-swagger-router-controller: "content"
  /hello:
    get:
      tags:
      - "Hello"
      description: "Returns 'Hello' to the caller"
      operationId: "hello"
      parameters:
      - name: "name"
        in: "query"
        description: "The name of the person to whom to say hello"
        required: false
        type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/HelloWorldResponse"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
      x-swagger-router-controller: "Hello"
    x-swagger-router-controller: "hello_world"
  /swagger:
    x-swagger-pipe: "swagger_raw"
definitions:
  HelloWorldResponse:
    required:
    - "message"
    properties:
      message:
        type: "string"
  ErrorResponse:
    required:
    - "message"
    properties:
      message:
        type: "string"
  node:
    properties:
      name:
        type: "object"
        properties: {}
  contentSchema:
    properties:
      children:
        type: "object"
        properties: {}
